[project]
name = "http-callout-sfdx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "click>=8.2.1",
  "python-dotenv>=1.1.1",
  "requests>=2.31.0",
  "rich>=14.0.0",
  "simple-salesforce>=1.12.6",
]
